/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as StatsRouteImport } from "./routes/stats";
import { Route as SettingsRouteImport } from "./routes/settings";
import { Route as ImportExportRouteImport } from "./routes/import-export";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as DecksNewRouteImport } from "./routes/decks.new";
import { Route as DecksDeckIdIndexRouteImport } from "./routes/decks.$deckId.index";
import { Route as DecksDeckIdStudyRouteImport } from "./routes/decks.$deckId.study";
import { Route as DecksDeckIdSettingsRouteImport } from "./routes/decks.$deckId.settings";
import { Route as DecksDeckIdAddRouteImport } from "./routes/decks.$deckId.add";
import { Route as CardsCardIdEditRouteImport } from "./routes/cards.$cardId.edit";

const StatsRoute = StatsRouteImport.update({
  id: "/stats",
  path: "/stats",
  getParentRoute: () => rootRouteImport,
} as any);
const SettingsRoute = SettingsRouteImport.update({
  id: "/settings",
  path: "/settings",
  getParentRoute: () => rootRouteImport,
} as any);
const ImportExportRoute = ImportExportRouteImport.update({
  id: "/import-export",
  path: "/import-export",
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const DecksNewRoute = DecksNewRouteImport.update({
  id: "/decks/new",
  path: "/decks/new",
  getParentRoute: () => rootRouteImport,
} as any);
const DecksDeckIdIndexRoute = DecksDeckIdIndexRouteImport.update({
  id: "/decks/$deckId/",
  path: "/decks/$deckId/",
  getParentRoute: () => rootRouteImport,
} as any);
const DecksDeckIdStudyRoute = DecksDeckIdStudyRouteImport.update({
  id: "/decks/$deckId/study",
  path: "/decks/$deckId/study",
  getParentRoute: () => rootRouteImport,
} as any);
const DecksDeckIdSettingsRoute = DecksDeckIdSettingsRouteImport.update({
  id: "/decks/$deckId/settings",
  path: "/decks/$deckId/settings",
  getParentRoute: () => rootRouteImport,
} as any);
const DecksDeckIdAddRoute = DecksDeckIdAddRouteImport.update({
  id: "/decks/$deckId/add",
  path: "/decks/$deckId/add",
  getParentRoute: () => rootRouteImport,
} as any);
const CardsCardIdEditRoute = CardsCardIdEditRouteImport.update({
  id: "/cards/$cardId/edit",
  path: "/cards/$cardId/edit",
  getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/import-export": typeof ImportExportRoute;
  "/settings": typeof SettingsRoute;
  "/stats": typeof StatsRoute;
  "/decks/new": typeof DecksNewRoute;
  "/cards/$cardId/edit": typeof CardsCardIdEditRoute;
  "/decks/$deckId/add": typeof DecksDeckIdAddRoute;
  "/decks/$deckId/settings": typeof DecksDeckIdSettingsRoute;
  "/decks/$deckId/study": typeof DecksDeckIdStudyRoute;
  "/decks/$deckId/": typeof DecksDeckIdIndexRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/import-export": typeof ImportExportRoute;
  "/settings": typeof SettingsRoute;
  "/stats": typeof StatsRoute;
  "/decks/new": typeof DecksNewRoute;
  "/cards/$cardId/edit": typeof CardsCardIdEditRoute;
  "/decks/$deckId/add": typeof DecksDeckIdAddRoute;
  "/decks/$deckId/settings": typeof DecksDeckIdSettingsRoute;
  "/decks/$deckId/study": typeof DecksDeckIdStudyRoute;
  "/decks/$deckId": typeof DecksDeckIdIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/import-export": typeof ImportExportRoute;
  "/settings": typeof SettingsRoute;
  "/stats": typeof StatsRoute;
  "/decks/new": typeof DecksNewRoute;
  "/cards/$cardId/edit": typeof CardsCardIdEditRoute;
  "/decks/$deckId/add": typeof DecksDeckIdAddRoute;
  "/decks/$deckId/settings": typeof DecksDeckIdSettingsRoute;
  "/decks/$deckId/study": typeof DecksDeckIdStudyRoute;
  "/decks/$deckId/": typeof DecksDeckIdIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/import-export"
    | "/settings"
    | "/stats"
    | "/decks/new"
    | "/cards/$cardId/edit"
    | "/decks/$deckId/add"
    | "/decks/$deckId/settings"
    | "/decks/$deckId/study"
    | "/decks/$deckId/";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/"
    | "/import-export"
    | "/settings"
    | "/stats"
    | "/decks/new"
    | "/cards/$cardId/edit"
    | "/decks/$deckId/add"
    | "/decks/$deckId/settings"
    | "/decks/$deckId/study"
    | "/decks/$deckId";
  id:
    | "__root__"
    | "/"
    | "/import-export"
    | "/settings"
    | "/stats"
    | "/decks/new"
    | "/cards/$cardId/edit"
    | "/decks/$deckId/add"
    | "/decks/$deckId/settings"
    | "/decks/$deckId/study"
    | "/decks/$deckId/";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  ImportExportRoute: typeof ImportExportRoute;
  SettingsRoute: typeof SettingsRoute;
  StatsRoute: typeof StatsRoute;
  DecksNewRoute: typeof DecksNewRoute;
  CardsCardIdEditRoute: typeof CardsCardIdEditRoute;
  DecksDeckIdAddRoute: typeof DecksDeckIdAddRoute;
  DecksDeckIdSettingsRoute: typeof DecksDeckIdSettingsRoute;
  DecksDeckIdStudyRoute: typeof DecksDeckIdStudyRoute;
  DecksDeckIdIndexRoute: typeof DecksDeckIdIndexRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/stats": {
      id: "/stats";
      path: "/stats";
      fullPath: "/stats";
      preLoaderRoute: typeof StatsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/settings": {
      id: "/settings";
      path: "/settings";
      fullPath: "/settings";
      preLoaderRoute: typeof SettingsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/import-export": {
      id: "/import-export";
      path: "/import-export";
      fullPath: "/import-export";
      preLoaderRoute: typeof ImportExportRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/decks/new": {
      id: "/decks/new";
      path: "/decks/new";
      fullPath: "/decks/new";
      preLoaderRoute: typeof DecksNewRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/decks/$deckId/": {
      id: "/decks/$deckId/";
      path: "/decks/$deckId";
      fullPath: "/decks/$deckId/";
      preLoaderRoute: typeof DecksDeckIdIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/decks/$deckId/study": {
      id: "/decks/$deckId/study";
      path: "/decks/$deckId/study";
      fullPath: "/decks/$deckId/study";
      preLoaderRoute: typeof DecksDeckIdStudyRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/decks/$deckId/settings": {
      id: "/decks/$deckId/settings";
      path: "/decks/$deckId/settings";
      fullPath: "/decks/$deckId/settings";
      preLoaderRoute: typeof DecksDeckIdSettingsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/decks/$deckId/add": {
      id: "/decks/$deckId/add";
      path: "/decks/$deckId/add";
      fullPath: "/decks/$deckId/add";
      preLoaderRoute: typeof DecksDeckIdAddRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/cards/$cardId/edit": {
      id: "/cards/$cardId/edit";
      path: "/cards/$cardId/edit";
      fullPath: "/cards/$cardId/edit";
      preLoaderRoute: typeof CardsCardIdEditRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ImportExportRoute: ImportExportRoute,
  SettingsRoute: SettingsRoute,
  StatsRoute: StatsRoute,
  DecksNewRoute: DecksNewRoute,
  CardsCardIdEditRoute: CardsCardIdEditRoute,
  DecksDeckIdAddRoute: DecksDeckIdAddRoute,
  DecksDeckIdSettingsRoute: DecksDeckIdSettingsRoute,
  DecksDeckIdStudyRoute: DecksDeckIdStudyRoute,
  DecksDeckIdIndexRoute: DecksDeckIdIndexRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

import type { getRouter } from "./router.tsx";
import type { startInstance } from "./start.ts";
declare module "@tanstack/react-start" {
  interface Register {
    ssr: true;
    router: Awaited<ReturnType<typeof getRouter>>;
    config: Awaited<ReturnType<typeof startInstance.getOptions>>;
  }
}
