/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SetsIndexRouteImport } from './routes/sets/index'
import { Route as SetsPostSlugRouteImport } from './routes/sets/$postSlug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SetsIndexRoute = SetsIndexRouteImport.update({
  id: '/sets/',
  path: '/sets/',
  getParentRoute: () => rootRouteImport,
} as any)
const SetsPostSlugRoute = SetsPostSlugRouteImport.update({
  id: '/sets/$postSlug',
  path: '/sets/$postSlug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sets/$postSlug': typeof SetsPostSlugRoute
  '/sets/': typeof SetsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sets/$postSlug': typeof SetsPostSlugRoute
  '/sets': typeof SetsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/sets/$postSlug': typeof SetsPostSlugRoute
  '/sets/': typeof SetsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/sets/$postSlug' | '/sets/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/sets/$postSlug' | '/sets'
  id: '__root__' | '/' | '/sets/$postSlug' | '/sets/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SetsPostSlugRoute: typeof SetsPostSlugRoute
  SetsIndexRoute: typeof SetsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sets/': {
      id: '/sets/'
      path: '/sets'
      fullPath: '/sets/'
      preLoaderRoute: typeof SetsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sets/$postSlug': {
      id: '/sets/$postSlug'
      path: '/sets/$postSlug'
      fullPath: '/sets/$postSlug'
      preLoaderRoute: typeof SetsPostSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SetsPostSlugRoute: SetsPostSlugRoute,
  SetsIndexRoute: SetsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
