packages:
    - 'assets/*' # assets management tools
    - 'backend/*'
    - 'frontend/*'
    - 'infrastructure/*'
    - 'shared/**/*'
    - 'tools/**/*' # internal toolig
allowBuilds:
    better-sqlite3: true
    esbuild: true
