/** Tags allowed after markdown/MDX compilation + sanitization. Keep in sync across export and frontend. */
export const ALLOWED_TAGS = [
    'h1',
    'h2',
    'h3',
    'h4',
    'h5',
    'h6',
    'p',
    'br',
    'hr',
    'b',
    'strong',
    'i',
    'em',
    'u',
    'del',
    'code',
    'pre',
    'blockquote',
    'ul',
    'ol',
    'li',
    'a',
    'img',
    'span',
    'div',
    'table',
    'thead',
    'tbody',
    'tr',
    'th',
    'td',
    // MDX component placeholders (compiled at export time)
    'aside',
    'figure',
    'figcaption',
] as const;

export const ALLOWED_ATTR = ['href', 'src', 'alt', 'title', 'class', 'target', 'rel'] as const;
